#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fib(num)
	sum = 0

	# Defining the first two numbers in the sequence
	prev = 0
	cur = 1


	while prev + cur < 4000000
		prev, cur = cur, prev + cur
		sum += cur if cur%2 == 0
	end
	# Returns sum
	sum
end

puts even_fib(15)
puts even_fib(4000000)